version: '3'

services:
    mosquitto:
        image: eclipse-mosquitto:2.0.15
        container_name: mosquitto
        restart: always
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge